### ISSUE TITLE
Failed installation in Mac Envrionement

### ISSUE THREAD

**Issue by takahi-i** [lunardog/kelner#4]
Hello,

I got the following error messages launching Kelner server. The message says libmagic is need and therefore I installed `libmagic` to my Mac envrionment  with `brew install libmagic` but still have the same problem. Would be helpful 

```
kelnerd -m tensorflow_inception_graph.pb --engine tensorflow --input-node ExpandDims --output-node softmax
Traceback (most recent call last):
  File "/Users/takahi-i/.pyenv/versions/3.6.0/bin/kelnerd", line 7, in <module>
    from kelner.cli import kelnerd
  File "/Users/takahi-i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/kelner/cli.py", line 4, in <module>
    from . import client
  File "/Users/takahi-i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/kelner/client.py", line 4, in <module>
    import magic
  File "/Users/takahi-i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by lunardog** [comment]
Could you send the output of this command: `brew info libmagic`?

I get this: 
```
libmagic: stable 5.33
Implementation of the file(1) command
https://www.darwinsys.com/file/
/opt/brew/Cellar/libmagic/5.32 (299 files, 6.0MB)
  Built from source on 2017-11-08 at 16:14:01
/opt/brew/Cellar/libmagic/5.33 (305 files, 6.2MB) *
  Built from source on 2018-04-27 at 11:38:31
From: /opt/brew/Library/Taps/homebrew/homebrew-core/Formula/libmagic.rb
==> Dependencies
Optional: python@2 ✔
==> Options
--with-python@2
        Build with python@2 support
```

**Comment by lunardog** [comment]
I think I can remove the libmagic dependency, which should solve your issue.

**Comment by takahi-i** [comment]
Sorry for the late response. The following is the results  of `brew info libmagic`.

```
brew info libmagic
libmagic: stable 5.33
Implementation of the file(1) command
https://www.darwinsys.com/file/
/opt/brew/Cellar/libmagic/5.33 (305 files, 6.2MB) *
  Built from source on 2018-07-11 at 15:44:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libmagic.rb
==> Dependencies
Optional: python@2 ✘
==> Options
--with-python@2
        Build with python@2 support
```

Thank you very much for your support!

**Comment by lunardog** [comment]
Until I remove the dependency, I can see two possible causes:

1. I'm not sure what the ✘ in your libmagic installation means:

Mine:`Optional: python@2 ✔`
Yours: `Optional: python@2 ✘`

2. It seems other people had this problem, caused by brew putting the library where python can't find it: http://www.brambraakman.com/blog/comments/installing_libmagic_in_mac_os_x_for_python-magic/

Anyway, I'm removing the dependency: https://github.com/lunardog/kelner/pull/5

**Comment by takahi-i** [comment]
I confirmed that the latest Kelner works in my environment. Thanks!
